### PR TITLE
Add smooth FOV changes

### PR DESCRIPTION
**Pull request by PlayeRom**

### CODE REVIEW

**Comment by slawekmikula** [comment]
Thanks a lot. Roman I suppose you know better that the code works as intended :) Looking at just the code style and placement I think it is OK to merge. I'll be merging it to my codebase.

As a sidenote. I'm rather short on time for FG. I wish I had more but RL is rather time consuming. If you would like to take the release process to your fork it's absolutely OK. Looking at your FG contribution (pl lang, logbook etc.) I think there should be no technical barriers but of course your time matters. Just a hint :) I'll have no much time for this in near future.

**Comment by PlayeRom** [comment]
OK, I can take care of that. Does it require any action for now?

**Comment by slawekmikula** [comment]
I think nothing but updating the info on the flightgear wiki page (https://wiki.flightgear.org/FGCamera). After that I'll mark in my repo the current one (yours) as a leading repository (if anyone will come here directly).

**Comment by PlayeRom** [comment]
Okay, I changed the github address on the wiki

**Comment by slawekmikula** [comment]
Added obsolete information in main readme on this repository. Thanks :)

**Pull request merged**
